# Generated by Django 4.0.2 on 2022-02-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
